config_map:     
  - name: PRODUCT
    value: "{{ product.name }}"    
  - name: OPENSHIFT_HOST_PORT
    value: "{{ openshift_host_port }}"                        
  - name: JAEGER_SERVICE_NAME
    value: "{{ project }}-{{ microservice.name }}"
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: "jaeger-agent.{{ product.name }}-monitoring.svc:5778"    
  - name: JAEGER_AGENT_HOST
    value: "jaeger-agent.{{ product.name }}-monitoring.svc"  
    
      